name: Install 7zip via vcpkg

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up vcpkg (if vcpkg isn't set up in your repo, clone it)
      - name: Set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      # Install 7zip using vcpkg
      - name: Install 7zip with vcpkg
        run: .\vcpkg\vcpkg install 7zip
