name: Install 7zip via vcpkg

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install 7zip with vcpkg
        shell: bash
        run: |
          #git clone https://github.com/microsoft/vcpkg.git
          #./vcpkg/bootstrap-vcpkg.bat
          export SystemDrive="$SYSTEMDRIVE"
          export SystemRoot="$SYSTEMROOT"
          export windir="$WINDIR"
          vcpkg install 7zip
