name: Install 7zip via vcpkg

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install 7zip using vcpkg
      - name: Install 7zip with vcpkg
        shell: bash
        run: |
          vcpkg install 7zip
